alias upd_workspace='cd ~/workspace_archlinux && git pull && source ~/workspace_archlinux/bashrc/bashrc && cd -'
alias upd_dwm='cd ~/srcpkgs/dwm_fork && git pull && sudo rm -rf /usr/local/bin/dwm && sudo rm -rf ~/srcpkgs/dwm_fork/config.h && sudo make clean install && cd -'
alias upd_grub='grub-mkconfig -o /boot/grub/grub.cfg'
alias upd_mirror_list='reflector --latest 20 --sort rate --save /etc/pacman.d/mirrorlist --age 24 --country "Vietnam,Singapore,Hong Kong" --fastest 8'

alias dockerosx='sh ~/workspace_archlinux/scripts/dockerosx/local_monterey.sh'
alias dockerosx_pull='sh ~/workspace_archlinux/scripts/dockerosx/online_monterey.sh'

alias install_base='sh ~/workspace_archlinux/scripts/installs/install_base.sh'
alias install_dockerosx='sh ~/workspace_archlinux/scripts/installs/install_dockerosx.sh'
alias install_dwm='sh ~/workspace_archlinux/scripts/installs/install_dwm.sh'
alias install_teazyou='sh ~/workspace_archlinux/scripts/installs/install_teazyou.sh'
