# EXPORTS
source $PATH_WORKSPACE/configs/zsh/exports

# VAR
source $PATH_WORKSPACE/configs/zsh/variables

# COLOR
source $PATH_WORKSPACE/configs/zsh/colors

# OH MY ZSH
plugins=(git)
ZSH_THEME="gallois"
source $ZSH/oh-my-zsh.sh

# NVM
source /usr/share/nvm/init-nvm.sh

# ALIAS
source $PATH_WORKSPACE/configs/zshrc/alias

# GIT
git config --global core.editor vim
git config --global user.email "$MAIL"